version: '2'

services: 
  opa-server:
    container_name: opa-server
    image: openpolicyagent/opa
    ports:
      - 8181:8181
    volumes:
      - ./polices/abac/:/polices
    command: 
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--log-level=debug"
      - "/polices"
